### ISSUE TITLE
WebAdministration Module - IIS Provider does not load in PowerShell 7 (P.4)

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShellModuleCoverage#14]
Steps to reproduce
------------------
After installing IIS.

```powershell
Import-Module WebAdministration
```

Expected behavior
-----------------

```none
It would load along with loading the provider
```

Actual behavior
---------------

```none
PS C:\Foo> import-module webadministration
import-module : Module 'C:\Windows\system32\WindowsPowerShell\v1.0\Modules\webadministration\webadministration.psd1' does not support current PowerShell edition 'Core'. Its supported editions are 'Desktop'. Use 'Import-Module -SkipEditionCheck' to ignore the compatibility of this module.
At line:1 char:1
+ import-module webadministration
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (C:\Windows\system32…administration.psd1:String) [Import-Module], InvalidOperationException
+ FullyQualifiedErrorId : Modules_PSEditionNotSupported,Microsoft.PowerShell.Commands.ImportModuleCommand
 
```

Environment data
----------------

```powershell
PS C:\Foo> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.4
PSEdition                      Core
GitCommitId                    7.0.0-preview.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0-preview.4}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by iSazonov** [comment]
You could try `Import-Module -SkipEditionCheck`.

**Comment by doctordns** [comment]
Great Idea, but...
```powershell
PS C:\Foo> import-module webadministration -SkipEditionCheck
import-module : Could not load type 'System.Management.Automation.PSSnapIn' from assembly 'System.Management.Automation, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
At line:1 char:1
+ import-module webadministration -SkipEditionCheck
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
+ FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by rjmholt** [comment]
> Great Idea, but...

Still good info to have. Thanks for trying that out.

I believe we are favouring the `IISAdministration` module for porting. Currently there are known issues with that module due to dependencies it takes that aren't in .NET Core 3.0 (although it's still closer to compatibility than `WebAdministration`). We're following up with the IIS team though to work out what the best way to make this module work in both Windows PowerShell and PowerShell 7. It's likely that other changes in PowerShell 7 will make it possible to use cmdlets from this module soon.

**Comment by doctordns** [comment]
Are we any closer to having this converted?

**Comment by abhiphirke** [comment]
Its been an year, do we have some news on this issue please? I too am stuck because of it.

**Comment by rjmholt** [comment]
@SteveL-MSFT

**Comment by doctordns** [comment]
Testing the latest Insider's build of Windows Server with the daily build of PowerShell 7 shows no improvement. The IISAdministration module loads and appears to work fine in PowerShell 7, but the WebAdministration is still not fully functioning.
All of the commands in the module appear to be available  7, but any returned objects are deserialize and the IIS: Provider is unavailable. 

As to 'stuck' - Any script that uses the WebAdministration module can be run using the built in Windows PowerShell 5.1 from the get go and you can always use the compatibility session to access this information, like this:

```powershell
PS C:\Foo> Import-Module -Name WebAdministration
PS C:\Foo> $S = Get-PSSession -Name WinPSCompatSession
PS C:\Foo> Invoke-Command -Session $S -ScriptBlock {Get-ChildItem -Path IIS:}

Name        PSComputerName
----        --------------
AppPools    localhost
Sites       localhost
SslBindings localhost
```

**Comment by andrei-shenets-simpligov** [comment]
It has been two years soon since the issue is reported. Any news?

**Comment by doctordns** [comment]
> It has been two years soon since the issue is reported. Any news?

No.

And no progress either.

I had hoped a fix might make it into Windows Server 2022. That appears not to have happened.

**Comment by davetapley** [comment]
I was able to do this in Windows 10, albeit with a slightly different error message:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
7      2      0      -1

PS C:\Users\azureuser> Get-ComputerInfo | select WindowsProductName, WindowsVersion, OsHardwareAbstractionLayer
>>

WindowsProductName WindowsVersion OsHardwareAbstractionLayer
------------------ -------------- --------------------------
Windows 10 Pro     2004           10.0.19041.1151




PS C:\Users\azureuser> Enable-WindowsOptionalFeature -featurename IIS-WebServer -online -all

PS C:\Users\azureuser> Import-Module webadministration
WARNING: Module webadministration is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
```

**Comment by mikegoatly** [comment]
The big issue with relying on the IISAdministration module is that it doesn't currently support adding/removing app pools (that I can see). This was what I was relying on the IIS: drive binding to do and without that, my scripts are going to be indefinitely stuck on PS 5.

**Comment by doctordns** [comment]
@mikegoatly - The underlying issue is with the IIS administration modules that do not load/operate property with PowerShell 7. Until Microsoft decide to update these two modules to fully work with PowerShell 7, there is not too much work that this repo can do to help. Sadly the issue needs to be filed elsewhere. 

The workaround is to use remoting. You can create a remoting session to the relevant machine, specifying a Windows PowerShell endpoint. Then use Invoke-Command to invoke the relevant script or script block in the remote session,. It is not particularly pretty, but it does work.

**Comment by tparikka** [comment]
@mikegoatly @doctordns I actually just struggled my way through this in PowerShell 7.2, and IISAdministration does allow for management of app pools and other elements of IIS in PS7. The trick is that unlike WebAdministration where there are cmdlets for every possible task, IISAdministration gives you a small set of cmdlets and then also the `Get-IISServerManager` command which returns a ServerManager and expects you to magically know what to do with it. [The documentation here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.administration.servermanager?view=iis-dotnet) is what saved me - essentially, the ServerManager returned by Get-IISServerManager is exactly the same as the .NET type that would be returned if you were mucking around in C#, and behaves more or less the same. Turns out that's the case for a ton of PowerShell 7 stuff, which was wild to me given I was totally new to PowerShell 3 weeks ago.

Give [this issue](https://github.com/PowerShell/PowerShell/issues/17012) a read first, I found in my case that if you don't install IISAdministration to the AllUsers scope it can screw up the module's ability to read in types from Microsoft.Web.Administration.dll.  Below is an example of an idempotent IIS setup script for my local copy of a secure token service (we're using IdentityServer) with a certificate included. If you have questions on any part of it, please reply. Any method I'm calling here should be available in the .NET API Browser link I provided, as well. I have tested this in PowerShell 7.2.1 and 7.2.2, no remoting required and no -UseWindowsPowerShell needed either.

```powershell
# Provision IIS

Write-Host "Installing IIS modules"
Enable-WindowsOptionalFeature -Online -FeatureName IIS-WebServerRole, IIS-WebServer, IIS-CommonHttpFeatures,
IIS-NetFxExtensibility45, IIS-HealthAndDiagnostics, IIS-HttpLogging, IIS-Performance, IIS-WebServerManagementTools,
IIS-ManagementScriptingTools, IIS-StaticContent, IIS-DefaultDocument, IIS-DirectoryBrowsing, IIS-ASPNET45,
IIS-ISAPIExtensions, IIS-ISAPIFilter, IIS-HttpCompressionStatic, IIS-ManagementConsole, IIS-WindowsAuthentication

# Initial import and setup

Write-Host "Importing modules"
Import-Module "IISAdministration"
$InitialLocation = Get-Location

# Clean up site instances
$LoginWebSiteName = "locallogin.mydomain.test"
Write-Host "Cleaning up old $LoginWebSiteName site and application pool."
$sm = Get-IISServerManager

$LoginWebSite = $sm.Sites[$LoginWebSiteName]
if ($null -ne $LoginWebSite) {
    $LoginWebSite.Delete()
}
$WebAppPool = $sm.ApplicationPools[$LoginWebSiteName];
if ($null -ne $WebAppPool) {
    $WebAppPool.Delete()
}

$sm.CommitChanges()

# Create certificates
Write-Host "Creating new certificates."
Set-Location "Cert:\LocalMachine\"
$CertificateDnsName = "*.mydomain.test"

Write-Host "Checking for root certificate."
$RootCertificate = (Get-ChildItem -Recurse | Where-Object { $_.Subject -like "*Local Certificate Authority*" })
[bool] $RootCertificateNew = $false

if (($null -eq $RootCertificate)) {
    Write-Host "Root certificate not found, generating certificate now."
    $RootCertificate = New-SelfSignedCertificate -KeyLength 4096 -HashAlgorithm "SHA512" -KeyExportPolicy Exportable -DnsName "Local Certificate Authority ($CertificateDnsName)" -KeyUsage CertSign -KeyUsageProperty Sign

    # This is needed because for some reason the certificate also gets created in the CA store.
    $DuplicateRootCertPath = [string]::Format('Cert:\LocalMachine\CA\{0}', $RootCertificate.Thumbprint)
    Remove-Item $DuplicateRootCertPath
    
    $RootCertificateNew = $true
}
else {
    Write-Host "Root certificate found, continuing."
}

Write-Host "Removing $CertificateDnsName certificates if expiring in less than 1 year."
$NewExpirationDate = (Get-Date).AddYears(10)
$NewExpirationDateFormatted = Get-Date($NewExpirationDate) -Format "yyyy-MM-dd"
Get-ChildItem -Recurse | Where-Object { ($_.FriendlyName -like "$CertificateDnsName*") -and ($_.NotAfter -lt (Get-Date).AddYears(1)) } | Remove-Item

$LoginLocalCertificate = (Get-ChildItem -Recurse | Where-Object { ($_.FriendlyName -like "$CertificateDnsName*") })
if (($null -eq $LoginLocalCertificate)) {
    Write-Host "Certificate for $CertificateDnsName site certificate not found or expires inside window, generating certificate now."
    Write-Host "New expiration date will be" $NewExpirationDateFormatted "."
    
    # Establish paths where root certificate will need to be shuffled
    $RootCertificatePathRoot = [string]::Format('Cert:\LocalMachine\Root\{0}', $RootCertificate.Thumbprint)
    $RootCertificatePathCA = [string]::Format('Cert:\LocalMachine\CA\{0}', $RootCertificate.Thumbprint)
    $RootCertificatePathMy = [string]::Format('Cert:\LocalMachine\My\{0}', $RootCertificate.Thumbprint)

    #Create new certificate
    if ($RootCertificateNew -eq $false) {
        $CertificateInRoot = Get-ChildItem -Path $RootCertificatePathRoot
        $CertificateInCA = Get-ChildItem -Path $RootCertificatePathCA

        if (($null -eq $CertificateInCa) -and ($null -ne $CertificateInRoot)) {
            Write-Host "Root certificate found only in $RootCertificatePathRoot, moving from Root."
            Move-Item -Path $RootCertificatePathRoot -Destination "Cert:\LocalMachine\My\"
        }
    }
    
    $LoginLocalCertificate = New-SelfSignedCertificate -KeyLength 2048 -HashAlgorithm "SHA256" -NotAfter $NewExpirationDateFormatted -DnsName $CertificateDnsName -FriendlyName $CertificateDnsName -KeySpec KeyExchange -Signer $RootCertificate

    Move-Item -Path $RootCertificatePathMy -Destination Cert:\LocalMachine\Root\
}
else {
    Write-Host "Certificate for $CertificateDnsName found and has at least one year remaining. Continuing."
}

$LoginLocalCertificateHashCode = $LoginLocalCertificate.GetCertHash()

# Create new sites and app pools
Write-Host "Creating new sites and application pools"
$sm = Get-IISServerManager
Set-Location $InitialLocation

$sm.ApplicationPools.Add($LoginWebSiteName)
$LoginWebSiteLocation = (Get-ChildItem | Where-Object { $_.Name -eq "IdentityServer" }).FullName
$LoginWebSite = $sm.Sites[$LoginWebSiteName]
$LoginWebSite = $sm.Sites.Add($LoginWebSiteName, "*:443:$LoginWebSiteName", $LoginWebSiteLocation, $LoginLocalCertificateHashCode)
$LoginWebSite.Applications["/"].ApplicationPoolName = $LoginWebSiteName

$sm.CommitChanges()

Write-Host "Site setup is complete. Enter any key to continue past IIS setup."
[Console]::ReadKey() | Out-Null
```

**Comment by mikegoatly** [comment]
@tparikka Yep, that all worked nicely. I had to jump through a few hoops to get the applicationHost environment variables set up for a specific site, so I've shared a couple of my [helper functions as a gist](https://gist.github.com/mikegoatly/2c8494c31b8522b73089896ca05ac42b) in case they are useful for others later.

**Comment by tparikka** [comment]
Thrilled to hear it! I am still hoping the PowerShell team joins the conversation now that we've solved the issue and can provide more insight into why the module is so gimmicky in regards to installation scope and provides better documentation around it.

**Comment by SetTrend** [comment]
@SteveL-MSFT: Are you monitoring this thread?

**Comment by Hem-Tark** [comment]
@tparikka Did you find a way to access AppPool's worker process which was available in the WebAdministration module's IIS: provider? I am dealing with the following scenario, 

After stopping the site with the `Stop-IISSite` command, all files which were being used by the site are not getting free. Some are still in use for a few seconds. I want those files to be free to proceed to the next step. So, I came up with the following solution,

I would access the worker process from the `IIS:\AppPools\<app_pool_name>\WorkerProcesses` and kill that process.

Is there a way to achieve this using IISAdministration?

**Comment by mikegoatly** [comment]
@Hem-Tark You can get the worker processes using the following:

``` powershell
Import-Module IISAdministration
$sm = Get-IISServerManager
$wp = $sm.WorkerProcesses
```

The data returned by WorkerProcesses looks like this:

```
ApplicationDomains : {}
AppPoolName        : MyApp
ProcessGuid        : 7aa61c3b-xxxx-xxxx-xxxx-0c2e6d8a0d9b
ProcessId          : 40200
State              : Running
Attributes         : {processId, guid, state, appPoolName}
ChildElements      : {appDomains}
ElementTagName     : workerProcess
IsLocallyStored    : False
Methods            : {GetRequests, GetCustomData}
RawAttributes      : {[processId, 40200], [guid, 7aa61c3b-xxxx-xxxx-xxxx-0c2e6d8a0d9b], [state, 1], [appPoolName,
                     MyApp]}
Schema             : Microsoft.Web.Administration.ConfigurationElementSchema
```

**Comment by Hem-Tark** [comment]
Thanks, @mikegoatly. This helped a lot.

**Comment by SteveL-MSFT** [comment]
Although perhaps not ideal, it seems that `IISAdministration` may be good enough as the `WebAdministration` module relies on APIs that are not planned to be supported in .NET (Core) so cannot be supported in PS7.

**Comment by jzabroski** [comment]
https://octopus.com/blog/iis-powershell#retry-retry-retry - the makers of Octopus Deploy have a detailed guide on the two approaches.

One interesting problem I discovered is that when you mix WebAdministration and IISAdministration in the same PowerShell session, it seems like you can enter a meta-table failure state where you will repeatedly get warnings that the state of the underlying xml representation of IIS Server State has changed...

```powershell
$sm = Get-iisservermanager;
$appPool = $sm.ApplicationPools["MyAppPool"];
$apppool.Enable32BitAppOnWin64 = $false;
$sm.CommitChanges();
```
