### ISSUE TITLE
System.Security.Cryptography.SHA256Cng fails to load

### ISSUE THREAD

**Issue by 3vi1** [PowerShell/PowerShellModuleCoverage#9]
# Steps to reproduce

(Note:  exact same results with up-to-date pwsh-preview.)

```
09:52:41 evil@P950ER ~/Downloads» pwsh
PowerShell 6.2.2
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /data/Downloads> install-module Microsoft.Graph.Intune
PS /data/Downloads> Import-Module Microsoft.Graph.Intune
PS /data/Downloads> Connect-MSGraph
```

# Expected behavior

```
I expected to be prompted for credentials and connect to the graph API.

```

# Actual behavior
```
Connect-MSGraph : Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
At line:1 char:1
+ Connect-MSGraph
+ ~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Connect-MSGraph], TypeLoadException
+ FullyQualifiedErrorId : System.TypeLoadException,Microsoft.Intune.PowerShellGraphSDK.PowerShellCmdlets.Connect

```

# Environment data

```Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Linux 5.2.0-8-generic #9-Ubuntu SMP Mon Jul 8 13:07:27 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```
This was tested with core 6 as well as the current pwsh-preview github build from source (as of 8/6/2019) as well as current pwsh & pwsh-preview snaps on Ubuntu 18.04 and Ubuntu 19.10 (Eoan Ermine).  See https://github.com/PowerShell/PowerShell/issues/10291.

**Comment by SteveL-MSFT** [comment]
@3vi1 thanks for reporting this, this module has it's own repo, I would suggest opening this issue there so they can take action.  https://github.com/Microsoft/Intune-PowerShell-SDK

**Comment by 3vi1** [comment]
@SteveL-MSFT I have done as you suggested, but since the System.Security.Cryptogrography namespace doesn't fall within their Intune module I'm not sure how they're supposed to fix it.  Is it deprecated or something and they shouldn't be using it?
